# Generated by Django 5.2.8 on 2025-11-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VTBBlago', '0003_helprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='date_created',
        ),
    ]
