# Generated by Django 5.2.8 on 2025-11-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTBBlago', '0005_project_category_project_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
