# Generated by Django 5.2.8 on 2025-11-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTBBlago', '0007_donation_anonymous_donation_user_user_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collected_all',
            field=models.BooleanField(default=False),
        ),
    ]
